name = "cloudflare-worker-2"
main = "index.js"
compatibility_date = "2025-02-24"
workers_dev = true

# Configure routes for seyahatmarket.com
routes = [
  "seyahatmarket.com/*",
  "www.seyahatmarket.com/*"
]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1
